spring:
  datasource:
    url: jdbc:sqlite:./data/students.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password:
  sql:
    init:
      platform: sqlite
      mode: embedded
      schema-locations: classpath:schema.sql
      encoding: utf-8
mybatis:
  type-aliases-package: com.cybb.bee.model
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080
